name: firewallreports
version: '1.0' 
summary: Log collector appliance for firewallreports.co.uk
description: |
  Log collector appliance for firewallreports.co.uk

#confinement: devmode

parts:
  logstash:
    plugin: dump
#    source: https://artifacts.elastic.co/downloads/logstash/logstash-6.2.4.tar.gz
    source: https://artifacts.elastic.co/downloads/logstash/logstash-5.6.9.tar.gz
#    organize:
#      conf/: $SNAP_DATA/conf/

    build-packages: 
    - ca-certificates
    - ca-certificates-java
    - openjdk-8-jre-headless

    override-build: |
      #env LOGSTASH_HOME=$SNAP JAVA_HOME=$SNAP/usr/lib/jvm/java-8-openjdk-$SNAP_ARCH
      ./bin/logstash-plugin install logstash-output-amazon_es
      snapcraftctl build      

    stage-packages:
    - ca-certificates
    - ca-certificates-java
    - openjdk-8-jre-headless
    - wget
    - jq
    - libc6

  wget:
    plugin: nil
    stage-packages:
      - wget

  jq:
    plugin: nil
    stage-packages:
      - jq


apps:

  logstash:
    command: |
      env LOGSTASH_HOME=$SNAP JAVA_HOME=$SNAP/usr/lib/jvm/java-8-openjdk-$SNAP_ARCH
      $SNAP/bin/logstash -f $SNAP_USER_DATA/logstash -l $SNAP_USER_COMMON 
    plugs: [network-bind, network, home]
    daemon: simple
    restart-condition: always
  
  wget:
    command: wget
    plugs: [network]

  jq:
    command: jq

hooks:
  install:
    plugs: [network]
